version: '3.7'

services:
  minio:
    hostname: minio
    image: 'minio/minio:latest'
    container_name: minio
    ports:
      - '9001:9001'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"
    networks:
      - bigdata_dev

networks:
  bigdata_dev:
    driver: bridge

volumes:
  minio-data:
    driver: local
